language: csharp
solution: VS2013_PROJECT/NZPortalWeb.sln

#dotnet: 1.0.1
mono: latest
#dist: trusty
sudo: enabled


# safelist
branches:
  only:
  - gmv

before_install:
  - sudo apt-get -qq update

install:
  - nuget restore VS2013_PROJECT/NZPortalWeb.sln

script:
   - xbuild /p:Configuration=Release VS2013_PROJECT/NZPortalWeb.sln