//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexsoIndex {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SettingsAppIndex : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsAppIndex defaultInstance = ((SettingsAppIndex)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsAppIndex())));
        
        public static SettingsAppIndex Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c1cd606c")]
        public string AppId {
            get {
                return ((string)(this["AppId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c7b04e68d5881311abf6e4d44fed7f10")]
        public string AppKey {
            get {
                return ((string)(this["AppKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\LuceneIndex")]
        public string LuceneFullPath {
            get {
                return ((string)(this["LuceneFullPath"]));
            }
        }
    }
}
