CREATE TABLE [dbo].[dnn_EasyDNNNewsArchive] (
    [HistoryEntryID]     INT             IDENTITY (1, 1) NOT NULL,
    [PortalID]           INT             NOT NULL,
    [UserID]             INT             NOT NULL,
    [Title]              NVARCHAR (800)  NOT NULL,
    [SubTitle]           NVARCHAR (4000) NULL,
    [Summary]            NVARCHAR (4000) NULL,
    [Article]            NVARCHAR (MAX)  NULL,
    [ArticleImage]       NVARCHAR (550)  NULL,
    [LastModified]       DATETIME        NULL,
    [PublishDate]        DATETIME        NULL,
    [ExpireDate]         DATETIME        NULL,
    [TitleLink]          NVARCHAR (400)  NULL,
    [DetailType]         NVARCHAR (50)   NULL,
    [DetailTypeData]     NVARCHAR (400)  NULL,
    [DetailsTemplate]    NVARCHAR (50)   NULL,
    [DetailsTheme]       NVARCHAR (50)   NULL,
    [GalleryPosition]    NVARCHAR (50)   NULL,
    [GalleryDisplayType] NVARCHAR (50)   NULL,
    [CommentsTheme]      NVARCHAR (50)   NULL,
    [ArticleImageFolder] NVARCHAR (250)  NULL,
    [HistoryVersion]     INT             NULL,
    [ArticleID]          INT             NULL,
    [Featured]           BIT             NOT NULL,
    [AllowComments]      BIT             NOT NULL,
    [ShowMainImage]      BIT             NOT NULL,
    [ShowMainImageFront] BIT             NOT NULL,
    CONSTRAINT [PK_dnn_EasyDNNNewsArchive_1] PRIMARY KEY CLUSTERED ([HistoryEntryID] ASC),
    CONSTRAINT [chk_dnn_EasyDNNNewsArchive_Title_Lenght] CHECK (len([Title])>(0)),
    CONSTRAINT [FK_dnn_EasyDNNNewsArchive_EasyDNNNews] FOREIGN KEY ([ArticleID]) REFERENCES [dbo].[dnn_EasyDNNNews] ([ArticleID]) ON DELETE CASCADE
);

