CREATE TABLE [dbo].[dnn_EasyDNNNewsSearchSettings] (
    [ModuleID]                    INT           NOT NULL,
    [SharingPortalID]             INT           NULL,
    [DisplayAllAuthors]           BIT           DEFAULT ((0)) NOT NULL,
    [NewsOrSearchModuleSource]    NVARCHAR (50) DEFAULT ('') NOT NULL,
    [SearchButtonPosition]        NVARCHAR (50) DEFAULT ('') NOT NULL,
    [DisplayStyle]                NVARCHAR (50) DEFAULT ('') NOT NULL,
    [HTMLTemplate]                NVARCHAR (50) DEFAULT ('') NOT NULL,
    [OpenInTab]                   NVARCHAR (50) DEFAULT ('') NOT NULL,
    [NumberOfChars]               INT           DEFAULT ((0)) NOT NULL,
    [SearchTemplate]              NVARCHAR (50) DEFAULT ('') NOT NULL,
    [SearchWay]                   NVARCHAR (50) DEFAULT ('') NOT NULL,
    [HighlightResults]            BIT           DEFAULT ((0)) NOT NULL,
    [DisplayResults]              NVARCHAR (50) DEFAULT ('') NOT NULL,
    [FormDisplay]                 NVARCHAR (50) DEFAULT ('') NOT NULL,
    [PermissionSource]            INT           DEFAULT ((0)) NOT NULL,
    [PermissionSourceID]          INT           DEFAULT ((0)) NOT NULL,
    [ShowAllCategories]           BIT           DEFAULT ((0)) NOT NULL,
    [AutoAddChildCategories]      BIT           DEFAULT ((0)) NOT NULL,
    [IsSocialInstance]            BIT           DEFAULT ((0)) NOT NULL,
    [HideUnlocalizedItems]        BIT           DEFAULT ((0)) NOT NULL,
    [AutoComplete]                BIT           DEFAULT ((0)) NOT NULL,
    [Imported]                    BIT           CONSTRAINT [DF_dnn_EasyDNNNewsSearchSettings_Imported] DEFAULT ((0)) NOT NULL,
    [SearchType]                  BIT           CONSTRAINT [DF_dnn_EasyDNNNewsSearchSettings_SearchType] DEFAULT ((0)) NOT NULL,
    [DisplayHeader]               BIT           CONSTRAINT [DF_dnn_EasyDNNNewsSearchSettings_DisplayHeader] DEFAULT ((0)) NOT NULL,
    [FieldsTemplateID]            INT           NULL,
    [UseCategoriesFieldTemplates] BIT           CONSTRAINT [DF_dnn_EasyDNNNewsSearchSettings_UseCategoriesFieldTemplates] DEFAULT ((0)) NOT NULL,
    [SearchArticles]              BIT           CONSTRAINT [DF_dnn_EasyDNNNewsSearchSettings_SearchArticles] DEFAULT ((1)) NOT NULL,
    [SearchEvents]                BIT           CONSTRAINT [DF_dnn_EasyDNNNewsSearchSettings_SearchEvents] DEFAULT ((1)) NOT NULL,
    [SearchEventsLimitByDays]     INT           NULL,
    [SearchOnlySelectedCFGroup]   BIT           CONSTRAINT [DF_dnn_EasyDNNNewsSearchSettings_SearchOnlySelectedCFGroup] DEFAULT ((0)) NOT NULL,
    [Visibility]                  TINYINT       CONSTRAINT [DF_dnn_EasyDNNNewsSearchSettings_Visibility] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dnn_EasyDNNNewsSearchSettings] PRIMARY KEY CLUSTERED ([ModuleID] ASC),
    CONSTRAINT [FK_dnn_EasyDNNNewsSearchSettings_EasyDNNfieldsTemplate] FOREIGN KEY ([FieldsTemplateID]) REFERENCES [dbo].[dnn_EasyDNNfieldsTemplate] ([FieldsTemplateID]) ON DELETE SET NULL,
    CONSTRAINT [FK_dnn_EasyDNNNewsSearchSettings_Modules] FOREIGN KEY ([ModuleID]) REFERENCES [dbo].[dnn_Modules] ([ModuleID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dnn_EasyDNNNewsSearchSettings_Portals] FOREIGN KEY ([SharingPortalID]) REFERENCES [dbo].[dnn_Portals] ([PortalID]) ON DELETE SET NULL,
    CONSTRAINT [IX_dnn_EasyDNNNewsSearchSettings] UNIQUE NONCLUSTERED ([ModuleID] ASC, [SharingPortalID] ASC)
);

