CREATE TABLE [dbo].[dnn_EasyGalleryGravityGallerySettings] (
    [SettingsID]                           INT            IDENTITY (1, 1) NOT NULL,
    [PortalID]                             INT            NOT NULL,
    [ModuleID]                             INT            NOT NULL,
    [ThemeName]                            NVARCHAR (150) NOT NULL,
    [ThemeFolder]                          NVARCHAR (550) NOT NULL,
    [ThemeCssFile]                         NVARCHAR (150) NOT NULL,
    [ThemeCssStlyeClass]                   NVARCHAR (50)  NOT NULL,
    [CategoryTemplate]                     NVARCHAR (150) NOT NULL,
    [GalleryTemplate]                      NVARCHAR (150) NOT NULL,
    [ItemTemplate]                         NVARCHAR (150) NOT NULL,
    [DetailsTemplate]                      NVARCHAR (150) NOT NULL,
    [DisplayCategories]                    BIT            NOT NULL,
    [CategoryThumbnailWidth]               INT            NOT NULL,
    [CategoryThumbnailHeight]              INT            NOT NULL,
    [NumberOfCategoryPagingLinks]          INT            NOT NULL,
    [Numberofcategoryitemsperpage]         INT            NOT NULL,
    [CategoryDisplayTitle]                 BIT            NOT NULL,
    [CategoryDisplayDescription]           BIT            NOT NULL,
    [CategoryDisplayAllGalleries]          BIT            NOT NULL,
    [CategoryDisplaySharingButtons]        BIT            NOT NULL,
    [CategoryDisplayNumberOfGalleries]     BIT            NOT NULL,
    [CategoryItemsSorting]                 INT            NOT NULL,
    [CategoryItemsSortingDirection]        INT            NOT NULL,
    [CategoryDisplayShowRss]               BIT            NOT NULL,
    [DisplayGalleries]                     BIT            NOT NULL,
    [DisplayItems]                         BIT            NOT NULL,
    [DisplayDetails]                       BIT            NOT NULL,
    [DetailsThumbnailWidth]                INT            NOT NULL,
    [DetailsThumbnailHeight]               INT            NOT NULL,
    [ItemsListThumbnailWidth]              INT            NOT NULL,
    [ItemsListThumbnailHeight]             INT            NOT NULL,
    [ItemsListDisplayTitle]                BIT            NOT NULL,
    [ItemsListDisplayDescription]          BIT            NOT NULL,
    [ItemsListDisplayUploaderInfo]         BIT            NOT NULL,
    [ItemsListDisplayItemNumberOfViews]    BIT            NOT NULL,
    [ItemsListDisplayNumberOfLikes]        BIT            NOT NULL,
    [ItemsListDisplayNumberOfDownloads]    BIT            NOT NULL,
    [ItemsListDisplayMediaRatingValue]     BIT            NOT NULL,
    [ItemsListDisplayItemsShareButtons]    BIT            NOT NULL,
    [ItemsListDisplayNumberOfComments]     BIT            NOT NULL,
    [ItemsListNumberOfCommentsToDisplay]   INT            NOT NULL,
    [ItemsListDisplayNewsLink]             BIT            NOT NULL,
    [ItemsListDisplayMediaType]            BIT            NOT NULL,
    [ItemsListDisplayShowRss]              BIT            NOT NULL,
    [ListItemsSorting]                     INT            NOT NULL,
    [ListItemsSortingDirection]            INT            NOT NULL,
    [ItemTitleLimit]                       INT            NOT NULL,
    [ItemDescriptionLimit]                 INT            NOT NULL,
    [GalleryThumbnailWidth]                INT            NOT NULL,
    [GalleryThumbnailHeight]               INT            NOT NULL,
    [GalleryDisplayAutorInfo]              BIT            NOT NULL,
    [GalleryDisplaySharingButtons]         BIT            NOT NULL,
    [GalleryDisplayNumberOfGalleryItems]   BIT            NOT NULL,
    [GalleryDisplayNumberOfGalleryImages]  BIT            NOT NULL,
    [GalleryDisplayNumberOfGalleryVideos]  BIT            NOT NULL,
    [GalleryDisplayNumberOfGalleryAudios]  BIT            NOT NULL,
    [GalleryDisplayNumberOfGalleryViews]   BIT            NOT NULL,
    [GalleryDisplayShowRss]                BIT            NOT NULL,
    [GalleryDisplayNewsLink]               BIT            NOT NULL,
    [GalleryItemsSorting]                  INT            NOT NULL,
    [GalleryItemsSortingDirection]         INT            NOT NULL,
    [GalleryTitleLimit]                    INT            NOT NULL,
    [GalleryDescriptionLimit]              INT            NOT NULL,
    [GalleryDisplayTitle]                  BIT            NOT NULL,
    [GalleryDisplayDescription]            BIT            NOT NULL,
    [Resizing]                             INT            NOT NULL,
    [LightboxType]                         INT            NOT NULL,
    [EmbedMedia]                           BIT            NOT NULL,
    [Numberofgalleryitemsperpage]          INT            NOT NULL,
    [Numberofgallerypaginglinks]           INT            NOT NULL,
    [NumberOfItemsListPagingLinks]         INT            NOT NULL,
    [NumberOfItemsListItemsPerPage]        INT            NOT NULL,
    [NumberOfRSSLinks]                     INT            NOT NULL,
    [IncludeImageInRssDescription]         BIT            NOT NULL,
    [AvatarSource]                         INT            NOT NULL,
    [CategoryTitleLimit]                   INT            NOT NULL,
    [CategoryDescriptionLimit]             INT            NOT NULL,
    [DetailsDisplayTitle]                  BIT            NOT NULL,
    [DetailsDisplayDescription]            BIT            NOT NULL,
    [DetailsDisplayUploaderInfo]           BIT            NOT NULL,
    [DetailsDisplayItemNumberOfViews]      BIT            NOT NULL,
    [DetailsDisplayNumberOfLikes]          BIT            NOT NULL,
    [DetailsDisplayNumberOfDownloads]      BIT            NOT NULL,
    [DetailsDisplayMediaRatingValue]       BIT            NOT NULL,
    [DetailsDisplayItemsShareButtons]      BIT            NOT NULL,
    [DetailsDisplayMediaType]              BIT            NOT NULL,
    [DetailsDisplayNewsLink]               BIT            NOT NULL,
    [DetailsDisplayNumberOfComments]       BIT            NOT NULL,
    [DetailsDisplayBreadCrumbs]            BIT            NOT NULL,
    [DetailsDisplayLikeButtons]            BIT            NOT NULL,
    [DetailsDisplayLikeButtonFacebook]     BIT            NOT NULL,
    [DetailsDisplayLikeButtonGooglePlus]   BIT            NOT NULL,
    [DetailsDisplayLikeButtonTwitter]      BIT            NOT NULL,
    [DetailsDisplayLikeButtonPinterest]    BIT            NOT NULL,
    [DetailsDisplayLikeButtonLinkedIn]     BIT            NOT NULL,
    [EnableGoogleMaps]                     BIT            NOT NULL,
    [MapsZoom]                             INT            NOT NULL,
    [MapsType]                             INT            NOT NULL,
    [MapsShowMarkerInfo]                   BIT            NOT NULL,
    [MapWidth]                             INT            NOT NULL,
    [MapWidthType]                         BIT            NOT NULL,
    [MapHeight]                            INT            NOT NULL,
    [PaginationType]                       TINYINT        NOT NULL,
    [DisplayUsersWhoLikedMedia]            BIT            NOT NULL,
    [NumberOfUsersWhoLikedMedia]           INT            NOT NULL,
    [DetailsDisplayExifData]               BIT            NOT NULL,
    [UseMasonryLayout]                     BIT            NOT NULL,
    [NewsModuleTabId]                      INT            NULL,
    [NewsModuleModuleId]                   INT            NULL,
    [GalleryDisplayBreadCrumbs]            BIT            NOT NULL,
    [PostCommentNotificationToJournal]     BIT            NOT NULL,
    [ItemListDisplayBreadCrumbs]           BIT            NOT NULL,
    [ItemsListDisplayLikeButtons]          BIT            NOT NULL,
    [ItemsListDisplayLikeButtonFacebook]   BIT            NOT NULL,
    [ItemsListDisplayLikeButtonGooglePlus] BIT            NOT NULL,
    [ItemsListDisplayLikeButtonTwitter]    BIT            NOT NULL,
    [ItemsListDisplayLikeButtonPinterest]  BIT            NOT NULL,
    [ItemsListDisplayLikeButtonLinkedIn]   BIT            NOT NULL,
    [EnableCommunityMode]                  BIT            NOT NULL,
    [PortalSharing]                        INT            NOT NULL,
    [UseCache]                             BIT            CONSTRAINT [DF_dnn_EasyGalleryGravityGallerySettings_UseCache] DEFAULT ((0)) NOT NULL,
    [ShowImages]                           BIT            CONSTRAINT [DF_dnn_EasyGalleryGravityGallerySettings_ShowImages] DEFAULT ((1)) NOT NULL,
    [ShowVideos]                           BIT            CONSTRAINT [DF_dnn_EasyGalleryGravityGallerySettings_ShowVideos] DEFAULT ((1)) NOT NULL,
    [ShowAudio]                            BIT            CONSTRAINT [DF_dnn_EasyGalleryGravityGallerySettings_ShowAudio] DEFAULT ((1)) NOT NULL,
    [ItemsListDisplayEmailLink]            BIT            CONSTRAINT [DF_dnn_EasyGalleryGravityGallerySettings_ItemsListDisplayEmailLink] DEFAULT ((0)) NOT NULL,
    [DetailsDisplayEmailLink]              BIT            CONSTRAINT [DF_dnn_EasyGalleryGravityGallerySettings_DetailsDisplayEmailLink] DEFAULT ((0)) NOT NULL,
    [ImportedModule]                       BIT            CONSTRAINT [DF_dnn_EasyGalleryGravityGallerySettings_ImportedModule] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dnn_EasyGalleryGravityGallerySettings] PRIMARY KEY CLUSTERED ([SettingsID] ASC),
    CONSTRAINT [FK_dnn_EasyGalleryGravityGallerySettings_dnn_Modules] FOREIGN KEY ([ModuleID]) REFERENCES [dbo].[dnn_Modules] ([ModuleID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dnn_EasyGalleryGravityGallerySettings_dnn_Portals] FOREIGN KEY ([PortalID]) REFERENCES [dbo].[dnn_Portals] ([PortalID]) ON DELETE CASCADE
);

