CREATE TABLE [dbo].[dnn_EasyDNNfields] (
    [CustomFieldID]          INT            IDENTITY (1, 1) NOT NULL,
    [ControlTypeID]          INT            NOT NULL,
    [CFParentID]             INT            NULL,
    [IsParent]               BIT            NOT NULL,
    [Name]                   NVARCHAR (300) NOT NULL,
    [PortalID]               INT            NOT NULL,
    [Token]                  NVARCHAR (250) NOT NULL,
    [DefText]                NVARCHAR (300) NULL,
    [DefRichText]            NVARCHAR (MAX) NULL,
    [DefDecimal]             NVARCHAR (250) NULL,
    [DefInteger]             INT            NULL,
    [DefBool]                BIT            NOT NULL,
    [ShowLabel]              BIT            NOT NULL,
    [LabelValue]             NVARCHAR (500) NOT NULL,
    [LabelHelp]              NVARCHAR (500) NOT NULL,
    [IconURL]                NVARCHAR (350) NULL,
    [IsPublished]            BIT            NOT NULL,
    [IsHidden]               BIT            NOT NULL,
    [IsSearchable]           BIT            NOT NULL,
    [IsRequired]             BIT            NOT NULL,
    [ValidationType]         INT            NOT NULL,
    [RegularExpression]      NVARCHAR (150) NOT NULL,
    [ValidationErrorMsg]     NVARCHAR (300) NULL,
    [ValidationFocusOnError] BIT            NULL,
    [DefDtime]               DATETIME       NULL,
    [FromValue]              INT            NULL,
    [ToValue]                INT            NULL,
    [ACode]                  NVARCHAR (5)   NULL,
    [RangeSource]            BIT            NULL,
    [FromLabel]              NVARCHAR (250) NULL,
    [ToLabel]                NVARCHAR (250) NULL,
    [DisplayFormat]          NVARCHAR (10)  NULL,
    [CommonDataID]           INT            NULL,
    [IsChilde]               BIT            CONSTRAINT [DF_dnn_EasyDNNfields_IsChilde] DEFAULT ((0)) NOT NULL,
    [ShowAllMultiElements]   BIT            CONSTRAINT [DF_dnn_EasyDNNfields_ShowAllMultiElements] DEFAULT ((0)) NOT NULL,
    [SearchLogicalOperator]  TINYINT        CONSTRAINT [DF_dnn_EasyDNNfields_SearchLogicalOperator] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_dnn_EasyDNNfields] PRIMARY KEY CLUSTERED ([CustomFieldID] ASC),
    CONSTRAINT [FK_dnn_EasyDNNfields_EasyDNNfields] FOREIGN KEY ([CFParentID]) REFERENCES [dbo].[dnn_EasyDNNfields] ([CustomFieldID]),
    CONSTRAINT [FK_dnn_EasyDNNfields_EasyDNNfielsType] FOREIGN KEY ([ControlTypeID]) REFERENCES [dbo].[dnn_EasyDNNfielsType] ([ControlTypeID]) ON DELETE CASCADE,
    CONSTRAINT [IX_dnn_EasyDNNfields_PortalID_Token] UNIQUE NONCLUSTERED ([PortalID] ASC, [Token] ASC)
);

