CREATE TABLE [dbo].[dnn_EasyGalleryPictures] (
    [PictureID]         INT             IDENTITY (1, 1) NOT NULL,
    [PortalID]          INT             NULL,
    [ModuleID]          INT             NOT NULL,
    [UserID]            INT             NULL,
    [GalleryID]         INT             NULL,
    [CategoryID]        INT             NULL,
    [Title]             NVARCHAR (250)  NULL,
    [Description]       NVARCHAR (MAX)  NULL,
    [FileName]          NVARCHAR (2500) NULL,
    [ThumbUrl]          NVARCHAR (250)  NULL,
    [Position]          INT             NULL,
    [MediaType]         NVARCHAR (30)   NULL,
    [ShortEmbedUrl]     NVARCHAR (250)  NULL,
    [ViewerThumb]       NVARCHAR (250)  NULL,
    [Info]              NVARCHAR (250)  NULL,
    [FileExtension]     NVARCHAR (5)    NULL,
    [ImageUrl]          NVARCHAR (1500) NULL,
    [ShowMedia]         NVARCHAR (5)    NULL,
    [GallerificThumb]   NVARCHAR (250)  NULL,
    [MediaApproved]     NVARCHAR (5)    NULL,
    [DateUploaded]      DATETIME        NULL,
    [StartupImage]      NVARCHAR (500)  NULL,
    [HiResVersion]      NVARCHAR (2500) NULL,
    [JournalId]         INT             NULL,
    [RatingCount]       INT             DEFAULT ((0)) NOT NULL,
    [RatingValue]       DECIMAL (18, 4) DEFAULT ((0)) NOT NULL,
    [NumberOfViews]     INT             CONSTRAINT [DF_dnn_EasyGalleryPictures_NumberOfViews] DEFAULT ((0)) NOT NULL,
    [NumberOfLikes]     INT             CONSTRAINT [DF_dnn_EasyGalleryPictures_NumberOfLikes] DEFAULT ((0)) NOT NULL,
    [NumberOfDownloads] INT             CONSTRAINT [DF_dnn_EasyGalleryPictures_NumberOfDownloads] DEFAULT ((0)) NOT NULL,
    [FileSize]          BIGINT          CONSTRAINT [DF_dnn_EasyGalleryPictures_FileSize] DEFAULT ((0)) NOT NULL,
    [ExifData]          NVARCHAR (MAX)  NULL,
    [GPSLatitude]       FLOAT (53)      NULL,
    [GPSLongitude]      FLOAT (53)      NULL,
    [VideoDuration]     INT             NULL,
    [Subtitle]          NVARCHAR (2000) NULL,
    CONSTRAINT [PK_dnn_EasyGalleryPictures] PRIMARY KEY CLUSTERED ([PictureID] ASC),
    CONSTRAINT [CK_dnn_EasyGalleryPicturesNumberOfLikes] CHECK ([NumberOfLikes]>=(0)),
    CONSTRAINT [FK_dnn_EasyGalleryPictures_dnn_Journal] FOREIGN KEY ([JournalId]) REFERENCES [dbo].[dnn_Journal] ([JournalId]) ON DELETE SET NULL,
    CONSTRAINT [FK_dnn_EasyGalleryPictures_EasyGallery] FOREIGN KEY ([GalleryID]) REFERENCES [dbo].[dnn_EasyGallery] ([GalleryID]) ON DELETE CASCADE
);



