CREATE TABLE [dbo].[dnn_Vendors] (
    [VendorId]      INT            IDENTITY (1, 1) NOT NULL,
    [VendorName]    NVARCHAR (50)  NOT NULL,
    [Street]        NVARCHAR (50)  NULL,
    [City]          NVARCHAR (50)  NULL,
    [Region]        NVARCHAR (50)  NULL,
    [Country]       NVARCHAR (50)  NULL,
    [PostalCode]    NVARCHAR (50)  NULL,
    [Telephone]     NVARCHAR (50)  NULL,
    [PortalId]      INT            NULL,
    [Fax]           NVARCHAR (50)  NULL,
    [Email]         NVARCHAR (50)  NULL,
    [Website]       NVARCHAR (100) NULL,
    [ClickThroughs] INT            CONSTRAINT [DF_dnn_Vendors_ClickThroughs] DEFAULT ((0)) NOT NULL,
    [Views]         INT            CONSTRAINT [DF_dnn_Vendors_Views] DEFAULT ((0)) NOT NULL,
    [CreatedByUser] NVARCHAR (100) NULL,
    [CreatedDate]   DATETIME       NULL,
    [LogoFile]      NVARCHAR (100) NULL,
    [KeyWords]      NTEXT          NULL,
    [Unit]          NVARCHAR (50)  NULL,
    [Authorized]    BIT            CONSTRAINT [DF_dnn_Vendors_Authorized] DEFAULT ((1)) NOT NULL,
    [FirstName]     NVARCHAR (50)  NULL,
    [LastName]      NVARCHAR (50)  NULL,
    [Cell]          VARCHAR (50)   NULL,
    CONSTRAINT [PK_dnn_Vendor] PRIMARY KEY CLUSTERED ([VendorId] ASC),
    CONSTRAINT [FK_dnn_Vendor_dnn_Portals] FOREIGN KEY ([PortalId]) REFERENCES [dbo].[dnn_Portals] ([PortalID]) ON DELETE CASCADE,
    CONSTRAINT [IX_dnn_Vendors] UNIQUE NONCLUSTERED ([PortalId] ASC, [VendorName] ASC)
);

