CREATE TABLE [dbo].[dnn_EasyDNNNewsTagCloudSettings] (
    [ModuleID]                  INT            NOT NULL,
    [SharingPortalID]           INT            NULL,
    [ShowTagCount]              BIT            DEFAULT ((0)) NOT NULL,
    [TagsByCategory]            BIT            DEFAULT ((0)) NOT NULL,
    [DisplayAllAuthors]         BIT            DEFAULT ((0)) NOT NULL,
    [DisplayHeader]             BIT            DEFAULT ((0)) NOT NULL,
    [PermissionSourceID]        INT            DEFAULT ((0)) NOT NULL,
    [PermissionSource]          INT            DEFAULT ((0)) NOT NULL,
    [DisplayStyle]              NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [AutoAddChildCategories]    BIT            DEFAULT ((0)) NOT NULL,
    [WhereToOpen]               NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [NumberOfTags]              INT            DEFAULT ((0)) NOT NULL,
    [Sorting]                   NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [OpenInModule]              NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [TagsTheme]                 NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [ShowAllCategories]         BIT            DEFAULT ((0)) NOT NULL,
    [IsSocialInstance]          BIT            DEFAULT ((0)) NOT NULL,
    [HtmTemplate]               NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [HideUnlocalizedItems]      BIT            DEFAULT ((0)) NOT NULL,
    [Imported]                  BIT            CONSTRAINT [DF_dnn_EasyDNNNewsTagCloudSettings_Imported] DEFAULT ((0)) NOT NULL,
    [TemplateGroup]             NVARCHAR (150) CONSTRAINT [DF_dnn_EasyDNNNewsTagCloudSettings_TemplateGroup] DEFAULT ('') NULL,
    [FilterByArticles]          BIT            CONSTRAINT [DF_dnn_EasyDNNNewsTagCloudSettings_FilterByArticles] DEFAULT ((1)) NOT NULL,
    [FilterByEvents]            BIT            CONSTRAINT [DF_dnn_EasyDNNNewsTagCloudSettings_FilterByEvents] DEFAULT ((1)) NOT NULL,
    [FilterByEventsLimitByDays] INT            NULL,
    [Visibility]                TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsTagCloudSettings_Visibility] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dnn_EasyDNNNewsTagCloudSettings] PRIMARY KEY CLUSTERED ([ModuleID] ASC),
    CONSTRAINT [FK_dnn_EasyDNNNewsTagCloudSettings_Modules] FOREIGN KEY ([ModuleID]) REFERENCES [dbo].[dnn_Modules] ([ModuleID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dnn_EasyDNNNewsTagCloudSettings_Portals] FOREIGN KEY ([SharingPortalID]) REFERENCES [dbo].[dnn_Portals] ([PortalID]) ON DELETE SET NULL,
    CONSTRAINT [IX_dnn_EasyDNNNewsTagCloudSettings] UNIQUE NONCLUSTERED ([ModuleID] ASC, [SharingPortalID] ASC)
);

