CREATE TABLE [dbo].[dnn_EasyDNNNewsPortalSettings] (
    [PortalID]                                 INT            NOT NULL,
    [ArticleApproveConfirm]                    BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_ArticleApproveConfirm] DEFAULT ((0)) NOT NULL,
    [CommentApproveConfirm]                    BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_CommentApproveConfirm] DEFAULT ((0)) NOT NULL,
    [TwitterConsumerKey]                       NVARCHAR (250) NULL,
    [TwitterConsumerSecret]                    NVARCHAR (250) NULL,
    [FacebookAppID]                            NVARCHAR (250) NULL,
    [FacebookAppSecret]                        NVARCHAR (250) NULL,
    [EnableTwitter]                            BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_EnableTwitter] DEFAULT ((0)) NOT NULL,
    [TwitterAccessToken]                       NVARCHAR (250) CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_TwitterAccessToken] DEFAULT ('') NULL,
    [TwitterAccessSecret]                      NVARCHAR (250) NULL,
    [EnableFacebook]                           BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_EnableFacebook] DEFAULT ((0)) NOT NULL,
    [FacebookAccessToken]                      NVARCHAR (250) NULL,
    [FacebookPostToIDAndToken]                 NVARCHAR (350) NULL,
    [EnableJournal]                            BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_EnableJournal] DEFAULT ((0)) NOT NULL,
    [EnableJournalComment]                     BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_EnableJournalComment] DEFAULT ((0)) NOT NULL,
    [PostSubtitleToJournal]                    BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_PostSubtitleToJournal] DEFAULT ((0)) NOT NULL,
    [PostSummaryToJournal]                     BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_PostSummaryToJournal] DEFAULT ((0)) NOT NULL,
    [PostTitleToJournal]                       BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_PostTitleToJournal] DEFAULT ((0)) NOT NULL,
    [PostImageToJournal]                       BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_PostImageToJournal] DEFAULT ((0)) NOT NULL,
    [ModuleToOpenUserActivity]                 INT            DEFAULT ((0)) NOT NULL,
    [ModuleToOpenGroupActivity]                INT            DEFAULT ((0)) NOT NULL,
    [IsSocialInstance]                         BIT            DEFAULT ((0)) NOT NULL,
    [PageTitleTemplate]                        NVARCHAR (150) DEFAULT (N'def') NOT NULL,
    [TitleItemSeparator]                       NVARCHAR (5)   DEFAULT (N'-') NOT NULL,
    [ModuleToOpenTwitterDetails]               INT            DEFAULT ((0)) NOT NULL,
    [ModuleToOpenFacebookDetails]              INT            DEFAULT ((0)) NOT NULL,
    [MapsUserLocationRequest]                  BIT            DEFAULT ((1)) NOT NULL,
    [ArticleDisplayControl]                    NVARCHAR (50)  DEFAULT ('ViewEasyDNNNews.ascx') NOT NULL,
    [NumberOfPosts]                            INT            DEFAULT ((5)) NOT NULL,
    [DisplayAsTable]                           BIT            DEFAULT ((0)) NOT NULL,
    [PostColumns]                              INT            DEFAULT ((1)) NOT NULL,
    [ColumnWidth]                              INT            DEFAULT ((250)) NOT NULL,
    [TotalNumberOfPosts]                       INT            DEFAULT ((0)) NOT NULL,
    [NumberOfPagerLinks]                       INT            DEFAULT ((10)) NOT NULL,
    [OpenInTab]                                NVARCHAR (50)  DEFAULT ('0') NOT NULL,
    [ShowPaging]                               BIT            DEFAULT ((1)) NOT NULL,
    [AllowComments]                            BIT            DEFAULT ((1)) NOT NULL,
    [ShowWrittenComments]                      BIT            DEFAULT ((1)) NOT NULL,
    [AllowArticleComments]                     BIT            DEFAULT ((0)) NOT NULL,
    [ShowCommentsRating]                       BIT            DEFAULT ((1)) NOT NULL,
    [ShowThreadedComments]                     BIT            DEFAULT ((1)) NOT NULL,
    [ApproveComments]                          BIT            DEFAULT ((0)) NOT NULL,
    [EnableCAPTCHA]                            BIT            DEFAULT ((0)) NOT NULL,
    [CommentsSource]                           NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [FacebookID]                               NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [FacebookNumOfComments]                    NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [FacebookColorScheme]                      NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [FacebookUserID]                           NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [DisqusID]                                 NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [DisqusOnline]                             BIT            DEFAULT ((1)) NOT NULL,
    [CommentsAvatarProvider]                   NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [FeaturedArticles]                         BIT            DEFAULT ((0)) NOT NULL,
    [FeaturedOnTop]                            BIT            DEFAULT ((0)) NOT NULL,
    [ShowAllCategories]                        BIT            DEFAULT ((1)) NOT NULL,
    [AutoAddChildCategories]                   BIT            DEFAULT ((0)) NOT NULL,
    [ShowAllAuthors]                           BIT            DEFAULT ((1)) NOT NULL,
    [ShowOnlyEvents]                           BIT            DEFAULT ((0)) NOT NULL,
    [PastEventsLimitDays]                      INT            DEFAULT ((0)) NOT NULL,
    [PastEventsLimit]                          NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [ModuleBoundToCategory]                    INT            DEFAULT ((0)) NOT NULL,
    [FilterByTags]                             BIT            DEFAULT ((0)) NOT NULL,
    [FilterByArticleID]                        BIT            DEFAULT ((0)) NOT NULL,
    [ShrinkThumb]                              BIT            DEFAULT ((0)) NOT NULL,
    [ShrinkMain]                               BIT            DEFAULT ((0)) NOT NULL,
    [ThumbImageWidth]                          INT            DEFAULT ((150)) NOT NULL,
    [ThumbImageHeight]                         INT            DEFAULT ((150)) NOT NULL,
    [MainImageWidth]                           INT            DEFAULT ((600)) NOT NULL,
    [MainImageHeight]                          INT            DEFAULT ((400)) NOT NULL,
    [ArticleImageJpegQuality]                  INT            DEFAULT ((97)) NOT NULL,
    [TokenResizeCrop]                          BIT            DEFAULT ((0)) NOT NULL,
    [TokenLightBox]                            BIT            DEFAULT ((0)) NOT NULL,
    [TokenTitle]                               BIT            DEFAULT ((0)) NOT NULL,
    [TokenDescription]                         BIT            DEFAULT ((0)) NOT NULL,
    [TokenCSSClass]                            NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [TokenWidth]                               INT            DEFAULT ((400)) NOT NULL,
    [TokenHeight]                              INT            DEFAULT ((400)) NOT NULL,
    [OrderPosts]                               NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [OrderPostsType]                           NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [EnableGalleryIntegration]                 BIT            DEFAULT ((0)) NOT NULL,
    [UseGalleryDefault]                        BIT            DEFAULT ((0)) NOT NULL,
    [GalleryPosition]                          NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [GalleryDisplayData]                       NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [UserCanSeeOnlyTheirGalleries]             BIT            DEFAULT ((0)) NOT NULL,
    [UserCanSeeOnlyTheirImages]                BIT            DEFAULT ((0)) NOT NULL,
    [ArticleDetailsTemplate]                   NVARCHAR (150) DEFAULT ('') NULL,
    [ArticleListTemplate]                      NVARCHAR (150) DEFAULT ('') NULL,
    [TemplatesFolder]                          NVARCHAR (150) DEFAULT ('') NULL,
    [ArticleListTheme]                         NVARCHAR (250) DEFAULT ('') NULL,
    [TemplatesFolderDetails]                   NVARCHAR (150) DEFAULT ('') NULL,
    [ArticleDetailsTheme]                      NVARCHAR (250) DEFAULT ('') NULL,
    [ArticleCommentsTemplate]                  NVARCHAR (250) DEFAULT ('') NULL,
    [ArticleDetailsDisplayStyle]               NVARCHAR (150) DEFAULT ('') NULL,
    [CommentsTheme]                            NVARCHAR (250) DEFAULT ('') NULL,
    [EnableThemeChange]                        BIT            DEFAULT ((0)) NOT NULL,
    [ShowInAllModules]                         BIT            DEFAULT ((0)) NOT NULL,
    [StaringArticle]                           INT            DEFAULT ((0)) NOT NULL,
    [OpenLinksInPage]                          NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [PassCategoryID]                           BIT            DEFAULT ((0)) NOT NULL,
    [OpenCategoryFirstArticle]                 BIT            DEFAULT ((0)) NOT NULL,
    [OpenFirstArticleByDate]                   BIT            DEFAULT ((0)) NOT NULL,
    [OpenCategoryArticleIfThereIsOnlyOne]      BIT            DEFAULT ((0)) NOT NULL,
    [OpenArticleByDateIfThereIsOnlyOne]        BIT            DEFAULT ((0)) NOT NULL,
    [OpenFirstArticle]                         BIT            DEFAULT ((0)) NOT NULL,
    [EnablePaidContent]                        BIT            DEFAULT ((0)) NOT NULL,
    [ShowCommentsOnPaidContent]                BIT            DEFAULT ((0)) NOT NULL,
    [ShowImageGalleryOnPaidContent]            BIT            DEFAULT ((0)) NOT NULL,
    [EnableRelatedArticles]                    BIT            DEFAULT ((0)) NOT NULL,
    [RelatedArticlesSorting]                   NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [NumberOfRelatedArticles]                  INT            DEFAULT ((5)) NOT NULL,
    [RSSUrl]                                   NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [InsertImageIntoRSS]                       BIT            DEFAULT ((0)) NOT NULL,
    [RssShowArticleImage]                      BIT            DEFAULT ((0)) NOT NULL,
    [RSSNumberOfArticles]                      INT            DEFAULT ((15)) NOT NULL,
    [RSSNumberOfCharacters]                    INT            DEFAULT ((15)) NOT NULL,
    [ShowRSSLink]                              BIT            DEFAULT ((0)) NOT NULL,
    [RSSArticleData]                           NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [SubtitleLimit]                            INT            DEFAULT ((0)) NOT NULL,
    [LimitTitleCharacters]                     INT            DEFAULT ((0)) NOT NULL,
    [LimitSummaryCharacters]                   INT            DEFAULT ((0)) NOT NULL,
    [ArticleLimit]                             INT            DEFAULT ((0)) NOT NULL,
    [ArticleRating]                            BIT            DEFAULT ((1)) NOT NULL,
    [ApproveArticles]                          BIT            DEFAULT ((0)) NOT NULL,
    [ApproveUpdatedArticles]                   BIT            DEFAULT ((0)) NOT NULL,
    [UserCanEditOnlyTheirArticles]             BIT            DEFAULT ((0)) NOT NULL,
    [AuthorsCanEditTheirOwnProfile]            BIT            DEFAULT ((0)) NOT NULL,
    [ShowAuthorsProfile]                       BIT            DEFAULT ((0)) NOT NULL,
    [ShowAuthorsGroupProfile]                  BIT            DEFAULT ((0)) NOT NULL,
    [EnableAuthorAliases]                      BIT            DEFAULT ((0)) NOT NULL,
    [AuthorsCanEditTheirOwnGroup]              BIT            DEFAULT ((0)) NOT NULL,
    [ImportedRSSShowAsLink]                    BIT            DEFAULT ((0)) NOT NULL,
    [OpenRSSLinksInNewWindow]                  BIT            DEFAULT ((0)) NOT NULL,
    [AddLinkToOriginalRSS]                     BIT            DEFAULT ((0)) NOT NULL,
    [ResizeUploadImage]                        BIT            DEFAULT ((0)) NOT NULL,
    [ImageResizeWidth]                         INT            DEFAULT ((100)) NOT NULL,
    [ImageResizeHeight]                        INT            DEFAULT ((100)) NOT NULL,
    [IsModuleSearchable]                       BIT            DEFAULT ((1)) NOT NULL,
    [IncludejQuery]                            BIT            DEFAULT ((0)) NOT NULL,
    [jQueryNoConflict]                         BIT            DEFAULT ((0)) NOT NULL,
    [numOfArticleHistory]                      INT            DEFAULT ((10)) NOT NULL,
    [DaylightSavingTime]                       BIT            DEFAULT ((0)) NOT NULL,
    [HideUnlocalizedItems]                     BIT            DEFAULT ((0)) NOT NULL,
    [DynamicModuleConatinerTitle]              BIT            DEFAULT ((0)) NOT NULL,
    [UserIDInLink]                             BIT            DEFAULT ((0)) NOT NULL,
    [ArticleListDisplayStyle]                  NVARCHAR (150) CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_ArticleListDisplayStyle] DEFAULT ('') NOT NULL,
    [CustomRoles]                              BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_CustomRoles] DEFAULT ((0)) NOT NULL,
    [ArticleListTemplateGroup]                 NVARCHAR (150) CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_ArticleListTemplateGroup] DEFAULT ('') NULL,
    [ArticleDetailsTemplateGroup]              NVARCHAR (150) CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_ArticleDetailsTemplateGroup] DEFAULT ('') NULL,
    [PublishDateValueType]                     TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_PublishDateValueType] DEFAULT ((0)) NOT NULL,
    [PublishDateValue]                         DATETIME       NULL,
    [ExpireDateValueType]                      TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_ExpireDateValueType] DEFAULT ((3)) NOT NULL,
    [ExpireDateValueToAdd]                     INT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_ExpireDateValueToAdd] DEFAULT ((1000)) NOT NULL,
    [ExpireDateValue]                          DATETIME       NULL,
    [CFUserSelectionType]                      TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_CFUserSelectionType] DEFAULT ((0)) NOT NULL,
    [CFSelectedGroup]                          INT            NULL,
    [CFEnableGroupSelection]                   BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_CFEnableGroupSelection] DEFAULT ((1)) NOT NULL,
    [GoogleAPIKey]                             NVARCHAR (300) NULL,
    [CategoriesSelectionExpanded]              BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_CategoriesSelectionExpanded] DEFAULT ((1)) NOT NULL,
    [MainNewsPaginationType]                   TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_MainNewsPaginationType] DEFAULT ((0)) NOT NULL,
    [EventsAddEditFormDefault]                 TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_EventsAddEditFormDefault] DEFAULT ((0)) NOT NULL,
    [ShowArticles]                             BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_ShowArticles] DEFAULT ((1)) NOT NULL,
    [ShowCommentsFromAllPortals]               BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_ShowCommentsFromAllPortals] DEFAULT ((1)) NOT NULL,
    [CFShowOnlyFilledItems]                    BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_CFShowOnlyFilledItems] DEFAULT ((0)) NOT NULL,
    [StripRSSHtml]                             BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_StripRSSHtml] DEFAULT ((1)) NOT NULL,
    [AutomaticallySetMainArticleImage]         BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_AutomaticallySetMainArticleImage] DEFAULT ((1)) NOT NULL,
    [AutomaticallyDisplayGalleryInArticle]     BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_AutomaticallyDisplayGalleryInArticle] DEFAULT ((1)) NOT NULL,
    [ArticleAuthorCommentApproveConfirm]       BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_ArticleAuthorCommentApproveConfirm] DEFAULT ((0)) NOT NULL,
    [GalleryCategoryID]                        INT            NULL,
    [ListDocumentsTemplate]                    NVARCHAR (250) NULL,
    [ListLinksTemplate]                        NVARCHAR (250) NULL,
    [ListRelatedArticlesTemplate]              NVARCHAR (250) NULL,
    [DetailsDocumentsTemplate]                 NVARCHAR (250) NULL,
    [DetailsLinksTemplate]                     NVARCHAR (250) NULL,
    [DetailsRelatedArticlesTemplate]           NVARCHAR (250) NULL,
    [CropResizeMode]                           TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_CropResizeMode] DEFAULT ((0)) NOT NULL,
    [EnableCanonicalLink]                      BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_EnableCanonicalLink] DEFAULT ((0)) NOT NULL,
    [RestrictionByDateRange]                   SMALLINT       NULL,
    [AdminFuturePostsVisible]                  BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_AdminFuturePostsVisible] DEFAULT ((0)) NOT NULL,
    [SendEventRegistrationInfoToArticleAuthor] BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_SendEventRegistrationInfoToArticleAuthor] DEFAULT ((1)) NOT NULL,
    [EventPostWhereToOpen]                     NVARCHAR (50)  NULL,
    [CreatePostLogFile]                        BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_CreatePostLogFile] DEFAULT ((0)) NOT NULL,
    [DefaultPostFromName]                      NVARCHAR (256) NULL,
    [DefaultPostFromMail]                      NVARCHAR (256) NULL,
    [DefaultReplyTo]                           NVARCHAR (256) NULL,
    [SubjectApprovalNeeded]                    NVARCHAR (256) NULL,
    [SubjectEventRegistration]                 NVARCHAR (256) NULL,
    [SubjectAwaitingApproval]                  NVARCHAR (256) NULL,
    [SubjectConfirm]                           NVARCHAR (256) NULL,
    [SubjectReject]                            NVARCHAR (256) NULL,
    [SubjectVerify]                            NVARCHAR (256) NULL,
    [TemplateApprovalNeeded]                   NVARCHAR (MAX) NULL,
    [TemplateEventRegistration]                NVARCHAR (MAX) NULL,
    [TemplateAwaitingApproval]                 NVARCHAR (MAX) NULL,
    [TemplateConfirm]                          NVARCHAR (MAX) NULL,
    [TemplateReject]                           NVARCHAR (MAX) NULL,
    [TemplateVerify]                           NVARCHAR (MAX) NULL,
    [GetAlreadyIndexedContent]                 BIT            CONSTRAINT [DF_dnn_EasyDNNNewsPortalSettings_GetAlreadyIndexedContent] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dnn_EasyDNNNewsPortalSettings] PRIMARY KEY CLUSTERED ([PortalID] ASC),
    CONSTRAINT [chk_dnn_EasyDNNNewsPortalSettings_RestrictionByDateRange] CHECK ([RestrictionByDateRange]>(0) OR [RestrictionByDateRange] IS NULL),
    CONSTRAINT [FK_dnn_EasyDNNNewsPortalSettings_EasyDNNfieldsTemplate] FOREIGN KEY ([CFSelectedGroup]) REFERENCES [dbo].[dnn_EasyDNNfieldsTemplate] ([FieldsTemplateID]),
    CONSTRAINT [FK_dnn_EasyDNNNewsPortalSettings_EasyGalleryCategoryID] FOREIGN KEY ([GalleryCategoryID]) REFERENCES [dbo].[dnn_EasyGalleryCategory] ([CategoryID]) ON DELETE SET NULL,
    CONSTRAINT [FK_dnn_EasyDNNNewsPortalSettings_Portals] FOREIGN KEY ([PortalID]) REFERENCES [dbo].[dnn_Portals] ([PortalID]) ON DELETE CASCADE
);

