CREATE TABLE [dbo].[dnn_EasyDNNNewsWidgetsFilterMenu] (
    [ModuleID]                  INT            NOT NULL,
    [SharingPortalID]           INT            NULL,
    [Theme]                     NVARCHAR (250) NOT NULL,
    [ThemeStyle]                NVARCHAR (250) NOT NULL,
    [ShowAllCategories]         BIT            NOT NULL,
    [AutoAddChildCategories]    BIT            NOT NULL,
    [DisplayAllAuthors]         BIT            NOT NULL,
    [Imported]                  BIT            NOT NULL,
    [OpenInTabID]               INT            NULL,
    [OpenInModuleID]            INT            NULL,
    [SelectionType]             TINYINT        NOT NULL,
    [PostBackType]              TINYINT        NOT NULL,
    [ShowOrderBy]               BIT            NOT NULL,
    [OrderBySelection]          NVARCHAR (100) NOT NULL,
    [HTMLTemplate]              NVARCHAR (250) NOT NULL,
    [ShowCategoryFilter]        BIT            NOT NULL,
    [ShowAuthorFilter]          BIT            NOT NULL,
    [ExpandAllCategories]       BIT            NOT NULL,
    [ExpandAllAuthors]          BIT            NOT NULL,
    [ArticlesCountByCategory]   BIT            NOT NULL,
    [ArticlesCountByAuthor]     BIT            NOT NULL,
    [FilterByArticles]          BIT            CONSTRAINT [DF_dnn_EasyDNNNewsWidgetsFilterMenu_FilterByArticles] DEFAULT ((1)) NOT NULL,
    [FilterByEvents]            BIT            CONSTRAINT [DF_dnn_EasyDNNNewsWidgetsFilterMenu_FilterByEvents] DEFAULT ((1)) NOT NULL,
    [FilterByEventsLimitByDays] INT            NULL,
    [UseANDOperatorByCategory]  BIT            CONSTRAINT [DF_dnn_EasyDNNNewsWidgetsFilterMenu_UseANDOperatorByCategory] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dnn_EasyDNNNewsWidgetsFilterMenu] PRIMARY KEY CLUSTERED ([ModuleID] ASC),
    CONSTRAINT [FK_dnn_EasyDNNNewsWidgetsFilterMenu_Modules] FOREIGN KEY ([ModuleID]) REFERENCES [dbo].[dnn_Modules] ([ModuleID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dnn_EasyDNNNewsWidgetsFilterMenu_Tabs] FOREIGN KEY ([OpenInTabID]) REFERENCES [dbo].[dnn_Tabs] ([TabID]) ON DELETE SET NULL
);

