CREATE TABLE [dbo].[dnn_EasyDNNNewsMenuSettings] (
    [ModuleID]               INT            NOT NULL,
    [SharingPortalID]        INT            NULL,
    [PassAuthorUserID]       BIT            DEFAULT ((0)) NOT NULL,
    [nodeExpandToLevel]      BIT            DEFAULT ((0)) NOT NULL,
    [nodeExpandLevel]        INT            DEFAULT ((1)) NOT NULL,
    [DisplayHeader]          BIT            DEFAULT ((0)) NOT NULL,
    [DisplayAllAuthors]      BIT            DEFAULT ((0)) NOT NULL,
    [CategoryMenuType]       NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [AutoAddChildCategories] BIT            DEFAULT ((0)) NOT NULL,
    [DisplayStyle]           NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [HTMLTemplate]           NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [WhereToOpen]            NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [DetailsModule]          NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [ModuleTheme]            NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [ShowAllCategories]      BIT            DEFAULT ((0)) NOT NULL,
    [ExpandAll]              BIT            DEFAULT ((0)) NOT NULL,
    [PermissionSource]       TINYINT        DEFAULT ((0)) NOT NULL,
    [PermissionSourceID]     INT            DEFAULT ((0)) NOT NULL,
    [IsSocialInstance]       BIT            DEFAULT ((0)) NOT NULL,
    [HideUnlocalizedItems]   BIT            DEFAULT ((0)) NOT NULL,
    [Imported]               BIT            CONSTRAINT [DF_dnn_EasyDNNNewsMenuSettings_Imported] DEFAULT ((0)) NOT NULL,
    [TemplateGroup]          NVARCHAR (150) CONSTRAINT [DF_dnn_EasyDNNNewsMenuSettings_TemplateGroup] DEFAULT ('') NULL,
    [CountArticles]          BIT            CONSTRAINT [DF_dnn_EasyDNNNewsMenuSettings_CountArticles] DEFAULT ((1)) NOT NULL,
    [CountEvents]            BIT            CONSTRAINT [DF_dnn_EasyDNNNewsMenuSettings_CountEvents] DEFAULT ((1)) NOT NULL,
    [CountEventsLimitByDays] INT            NULL,
    [Visibility]             TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsMenuSettings_Visibility] DEFAULT ((0)) NOT NULL,
    [ShowEmptyCategories]    BIT            CONSTRAINT [DF_dnn_EasyDNNNewsMenuSettings_ShowEmptyCategories] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_dnn_EasyDNNNewsMenuSettings] PRIMARY KEY CLUSTERED ([ModuleID] ASC),
    CONSTRAINT [FK_dnn_EasyDNNNewsMenuSettings_Modules] FOREIGN KEY ([ModuleID]) REFERENCES [dbo].[dnn_Modules] ([ModuleID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dnn_EasyDNNNewsMenuSettings_Portals] FOREIGN KEY ([SharingPortalID]) REFERENCES [dbo].[dnn_Portals] ([PortalID]) ON DELETE SET NULL,
    CONSTRAINT [IX_dnn_EasyDNNNewsMenuSettings] UNIQUE NONCLUSTERED ([ModuleID] ASC, [SharingPortalID] ASC)
);

