CREATE TABLE [dbo].[dnn_EasyDNNNewsCalendarSettings] (
    [ModuleID]                         INT            NOT NULL,
    [SharingPortalID]                  INT            NULL,
    [UpcomingEventsTTSummaryLenght]    INT            DEFAULT ((0)) NOT NULL,
    [CalendarTooltipSummaryLenght]     INT            DEFAULT ((0)) NOT NULL,
    [ShowEventsBypublishDate]          BIT            DEFAULT ((0)) NOT NULL,
    [CalendarEventsExportIcon]         BIT            DEFAULT ((0)) NOT NULL,
    [UpcomingEventsToolTip]            BIT            DEFAULT ((0)) NOT NULL,
    [ShowUpcomingEventsRSSIcon]        BIT            DEFAULT ((0)) NOT NULL,
    [ShowUpcomingEventsExportIcon]     BIT            DEFAULT ((0)) NOT NULL,
    [CellHeight]                       INT            DEFAULT ((0)) NOT NULL,
    [TitleLenght]                      INT            DEFAULT ((0)) NOT NULL,
    [NumOfItemsInCell]                 INT            DEFAULT ((0)) NOT NULL,
    [ShowNewsRSSLink]                  BIT            DEFAULT ((0)) NOT NULL,
    [ShowEventRSSLink]                 BIT            DEFAULT ((0)) NOT NULL,
    [ShowListLink]                     BIT            DEFAULT ((0)) NOT NULL,
    [DisplayHeaderEvents]              BIT            DEFAULT ((0)) NOT NULL,
    [PastEventsLimitDays]              INT            DEFAULT ((0)) NOT NULL,
    [PastEventsLimit]                  NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [ShowEventsInCalendar]             BIT            DEFAULT ((0)) NOT NULL,
    [ShowArticlesInCalendar]           BIT            DEFAULT ((0)) NOT NULL,
    [OpenEventDetails]                 NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [NumberOfEventsToShow]             INT            DEFAULT ((0)) NOT NULL,
    [ShowEventArchive]                 BIT            DEFAULT ((0)) NOT NULL,
    [DisplayAllAuthors]                BIT            DEFAULT ((0)) NOT NULL,
    [DisplayHeader]                    BIT            DEFAULT ((0)) NOT NULL,
    [PermissionSourceID]               INT            DEFAULT ((0)) NOT NULL,
    [PermissionSource]                 TINYINT        DEFAULT ((0)) NOT NULL,
    [AutoAddChildCategories]           BIT            DEFAULT ((0)) NOT NULL,
    [ShowAllCategories]                BIT            DEFAULT ((0)) NOT NULL,
    [DisplayStyle]                     NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [MonthlyArchiveModule]             NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [MonthlyShowArchive]               BIT            DEFAULT ((0)) NOT NULL,
    [ShowCalendarArchive]              BIT            DEFAULT ((0)) NOT NULL,
    [WhereToOpen]                      NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [ModuleTheme]                      NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [DetailsModule]                    NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [FirstDayOfTheWeek]                NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [IsSocialInstance]                 BIT            DEFAULT ((0)) NOT NULL,
    [IsTooltipEnabled]                 BIT            DEFAULT ((0)) NOT NULL,
    [CalendarType]                     TINYINT        DEFAULT ((0)) NOT NULL,
    [HideUnlocalizedItems]             BIT            DEFAULT ((0)) NOT NULL,
    [Imported]                         BIT            CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_Imported] DEFAULT ((0)) NOT NULL,
    [ArchiveTypeOfView]                TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_ArchiveTypeOfView] DEFAULT ((0)) NOT NULL,
    [ArchiveTemplate]                  NVARCHAR (250) CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_ArchiveTemplate] DEFAULT ('') NOT NULL,
    [ArchiveExpandMode]                TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_ArchiveExpandMode] DEFAULT ((0)) NOT NULL,
    [ArchiveTemplateGroup]             NVARCHAR (150) CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_ArchiveTemplateGroup] DEFAULT ('') NULL,
    [ArchiveOnlyArticles]              BIT            CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_ArchiveOnlyArticles] DEFAULT ((1)) NOT NULL,
    [ArchiveOnlyEvents]                BIT            CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_ArchiveOnlyEvents] DEFAULT ((1)) NOT NULL,
    [ArchiveCountEventsLimitByDays]    INT            NULL,
    [ShowUpcomingEventsPortalTimeZone] BIT            CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_ShowUpcomingEventsPortalTimeZone] DEFAULT ((0)) NOT NULL,
    [ShowCalendarPortalTimeZone]       BIT            CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_ShowCalendarPortalTimeZone] DEFAULT ((0)) NOT NULL,
    [Visibility]                       TINYINT        CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_Visibility] DEFAULT ((0)) NOT NULL,
    [CalendarUserIDInLink]             BIT            CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_CalendarUserIDInLink] DEFAULT ((0)) NOT NULL,
    [UpcomingEventsUserIDInLink]       BIT            CONSTRAINT [DF_dnn_EasyDNNNewsCalendarSettings_UpcomingEventsUserIDInLink] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dnn_EasyDNNNewsCalendarSettings] PRIMARY KEY CLUSTERED ([ModuleID] ASC),
    CONSTRAINT [FK_dnn_EasyDNNNewsCalendarSettings_Modules] FOREIGN KEY ([ModuleID]) REFERENCES [dbo].[dnn_Modules] ([ModuleID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dnn_EasyDNNNewsCalendarSettings_Portals] FOREIGN KEY ([SharingPortalID]) REFERENCES [dbo].[dnn_Portals] ([PortalID]) ON DELETE SET NULL,
    CONSTRAINT [IX_dnn_EasyDNNNewsCalendarSettings] UNIQUE NONCLUSTERED ([ModuleID] ASC, [SharingPortalID] ASC)
);

