CREATE TABLE [dbo].[dnn_EasyGalleryPortfolioProSettings] (
    [SettingsID]                INT            IDENTITY (1, 1) NOT NULL,
    [PortalID]                  INT            NOT NULL,
    [ModuleID]                  INT            NOT NULL,
    [CategoryID]                INT            NOT NULL,
    [GalleryID]                 INT            NOT NULL,
    [ThumbnailWidth]            INT            NOT NULL,
    [ThumbnailHeight]           INT            NOT NULL,
    [ShowTitle]                 BIT            NOT NULL,
    [ShowDescription]           BIT            NOT NULL,
    [ItemsPerPage]              INT            NOT NULL,
    [DisplayNestedGalleries]    BIT            NOT NULL,
    [DisplayAllNestedGalleries] BIT            NOT NULL,
    [NestedAnimationType]       INT            NOT NULL,
    [CaptionAnimation]          INT            NOT NULL,
    [GridAdjustment]            INT            NOT NULL,
    [ItemsGapHorizontal]        INT            NOT NULL,
    [ItemsGapVertical]          INT            NOT NULL,
    [ImagesDisplayType]         INT            NOT NULL,
    [DisplayTypeSpeed]          INT            NOT NULL,
    [LightboxType]              INT            NOT NULL,
    [ShowImageCounter]          BIT            NOT NULL,
    [ShowTitleInLightbox]       BIT            NOT NULL,
    [NestedNavigationType]      INT            NOT NULL,
    [ShowSubtitle]              BIT            NOT NULL,
    [TempalteName]              NVARCHAR (255) NOT NULL,
    [GridClass]                 NVARCHAR (20)  NOT NULL,
    [LiClass]                   NVARCHAR (20)  NOT NULL,
    [InlinePosition]            INT            NOT NULL,
    [CssTheme]                  NVARCHAR (255) NOT NULL,
    [MediaSorting]              NVARCHAR (15)  NOT NULL,
    [MediaSortingAscType]       NVARCHAR (4)   NOT NULL,
    [ImportedModule]            BIT            NOT NULL,
    [ShowGalleryMediaCounter]   BIT            CONSTRAINT [DF_dnn_EasyGalleryPortfolioProSettings_ShowGalleryMediaCounter] DEFAULT ((1)) NOT NULL,
    [PortalSharing]             INT            NULL,
    [JpegQuality]               INT            CONSTRAINT [DF_dnn_EasyGalleryPortfolioProSettings_JpegQuality] DEFAULT ((97)) NOT NULL,
    [ShowAllButton]             BIT            CONSTRAINT [DF_dnn_EasyGalleryPortfolioProSettings_ShowAllButton] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_dnn_EasyGalleryPortfolioProSettings] PRIMARY KEY CLUSTERED ([SettingsID] ASC),
    CONSTRAINT [FK_dnn_EasyGalleryPortfolioProSettings_dnn_Modules] FOREIGN KEY ([ModuleID]) REFERENCES [dbo].[dnn_Modules] ([ModuleID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dnn_EasyGalleryPortfolioProSettings_dnn_Portals] FOREIGN KEY ([PortalID]) REFERENCES [dbo].[dnn_Portals] ([PortalID]) ON DELETE CASCADE
);

