CREATE TABLE [dbo].[dnn_EasyDNNNewsEventsData] (
    [ArticleID]                  INT           NOT NULL,
    [StartDate]                  DATETIME      NOT NULL,
    [EndDate]                    DATETIME      NOT NULL,
    [WhloeDay]                   BIT           NOT NULL,
    [ShowEndDate]                BIT           DEFAULT ((1)) NOT NULL,
    [Recurring]                  BIT           CONSTRAINT [DF_dnn_EasyDNNNewsEventsData_Recurring] DEFAULT ((0)) NOT NULL,
    [RecurringType]              TINYINT       NULL,
    [RecurringHour]              INT           NULL,
    [RecurringDay]               INT           NULL,
    [RecurringWeek]              INT           NULL,
    [RecurringWeekDays]          NVARCHAR (20) NULL,
    [RecurringMonthType]         TINYINT       NULL,
    [RecurringMonthDay]          TINYINT       NULL,
    [RecurringMonthDayOfWeek]    TINYINT       NULL,
    [RecurringMonth]             INT           NULL,
    [RecurringYearType]          TINYINT       NULL,
    [RecurringYearMonthDay]      TINYINT       NULL,
    [RecurringYearDayOfWeek]     TINYINT       NULL,
    [RecurringYearMonth]         TINYINT       NULL,
    [RecurringYear]              INT           NULL,
    [RecurringEndType]           TINYINT       NULL,
    [RecurringEndByDate]         DATETIME      NULL,
    [EndsAfterOccurrences]       INT           NULL,
    [UpcomingOccurrences]        INT           NULL,
    [ReccuringInEditMode]        BIT           NULL,
    [EventType]                  TINYINT       NULL,
    [MaxNumberOfTickets]         INT           NULL,
    [EnableDaysBeforeStartDate]  INT           NULL,
    [DisableDaysBeforeStartDate] INT           NULL,
    [EventRegisterMinTickets]    INT           NULL,
    [EventRegisterMaxTickets]    INT           NULL,
    [RegistrationType]           TINYINT       NULL,
    [EventRegistrationRole]      INT           NULL,
    [RegistrationApproval]       BIT           NULL,
    [DisableFurtherRegistration] BIT           NULL,
    [ShowRegistredUsersRole]     INT           NULL,
    [ShowRegistredUsersTo]       TINYINT       NULL,
    [RegistrationCFtemplateID]   INT           NULL,
    CONSTRAINT [PK_dnn_easynewsEvent] PRIMARY KEY CLUSTERED ([ArticleID] ASC),
    CONSTRAINT [FK_dnn_easynewsEvent_EasyDNNNews] FOREIGN KEY ([ArticleID]) REFERENCES [dbo].[dnn_EasyDNNNews] ([ArticleID]) ON DELETE CASCADE
);

