//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexsoServices.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexsoServices.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; style=&quot;font-family: &apos;Helvetica Neue&apos;, &apos;Helvetica&apos;, Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0; padding: 0;&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;New message&lt;/title&gt;
        ///
        ///
        ///    &lt;style type=&quot;tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailBodyConfirmation {
            get {
                return ResourceManager.GetString("EmailBodyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Like.
        /// </summary>
        internal static string LikeNotification {
            get {
                return ResourceManager.GetString("LikeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; style=&quot;font-family: &apos;Helvetica Neue&apos;, &apos;Helvetica&apos;, Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0; padding: 0;&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;title&gt;New comment&lt;/title&gt;
        ///
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///img {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageBodyComment {
            get {
                return ResourceManager.GetString("MessageBodyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; style=&quot;font-family: &apos;Helvetica Neue&apos;, &apos;Helvetica&apos;, Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0; padding: 0;&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;title&gt;New message&lt;/title&gt;
        ///
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///img {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageBodyMessage {
            get {
                return ResourceManager.GetString("MessageBodyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification message.
        /// </summary>
        internal static string MessageNotification {
            get {
                return ResourceManager.GetString("MessageNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} commented on {1}.
        /// </summary>
        internal static string MessageTitleComment {
            get {
                return ResourceManager.GetString("MessageTitleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has sent you a new message.
        /// </summary>
        internal static string MessageTitleMessage {
            get {
                return ResourceManager.GetString("MessageTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {UserName}&lt;/p&gt;
        ///
        ///&lt;p&gt;You have voted for the solution &lt;a href=&apos;https://www.nexso.org/en-us/SolProfile/sl/{SolutionId}&apos;&gt;{SolutionTitle}&lt;/a&gt;. Please click the following link to verify your e-mail..&lt;/p&gt;
        ///&lt;p&gt;
        ///    &lt;a href=&apos;https://www.nexso.org/en-us/SolProfile/sl/{SolutionId}/ottpyPc/{PotentialUserId}/oztptTo/{Token}&apos; target=&quot;_blank&quot; style=&quot;font-family:&apos;Helvetica Neue&apos;,&apos;Helvetica&apos;,Helvetica,Arial,sans-serif; font-size:14px; color:#FFF; text-decoration:none; line-height:2; font-weight:bold; text-align:ce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOLUTIONEmailConfirmationVOTEBody {
            get {
                return ResourceManager.GetString("SOLUTIONEmailConfirmationVOTEBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your vote.
        /// </summary>
        internal static string SOLUTIONEmailConfirmationVOTESubject {
            get {
                return ResourceManager.GetString("SOLUTIONEmailConfirmationVOTESubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ATTACHED_USER} commented in your solution {SOLUTION}.
        /// </summary>
        internal static string SOLUTIONMessageCOMMENTV1 {
            get {
                return ResourceManager.GetString("SOLUTIONMessageCOMMENTV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ATTACHED_USER} likes your solution {SOLUTION}..
        /// </summary>
        internal static string SOLUTIONMessageLIKEV1 {
            get {
                return ResourceManager.GetString("SOLUTIONMessageLIKEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ATTACHED_USER} has sent you a message..
        /// </summary>
        internal static string SOLUTIONMessageMESSAGEV1 {
            get {
                return ResourceManager.GetString("SOLUTIONMessageMESSAGEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ATTACHED_USER} rated your solution {SOLUTION}..
        /// </summary>
        internal static string SOLUTIONMessageRATEV1 {
            get {
                return ResourceManager.GetString("SOLUTIONMessageRATEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SOLUTIONToolTipCOMMENTV1 {
            get {
                return ResourceManager.GetString("SOLUTIONToolTipCOMMENTV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SOLUTIONToolTipLIKEV1 {
            get {
                return ResourceManager.GetString("SOLUTIONToolTipLIKEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SOLUTIONToolTipMESSAGEV1 {
            get {
                return ResourceManager.GetString("SOLUTIONToolTipMESSAGEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SOLUTIONToolTipRATEDV1 {
            get {
                return ResourceManager.GetString("SOLUTIONToolTipRATEDV1", resourceCulture);
            }
        }
    }
}
