CREATE TABLE [dbo].[PotentialUsers] (
    [PotentialUserId]  UNIQUEIDENTIFIER NOT NULL,
    [Email]            VARCHAR (100)    NULL,
    [FirstName]        VARCHAR (100)    NULL,
    [LastName]         VARCHAR (100)    NULL,
    [MiddleName]       VARCHAR (100)    NULL,
    [Phone]            VARCHAR (100)    NULL,
    [Address]          VARCHAR (400)    NULL,
    [Country]          VARCHAR (100)    NULL,
    [Region]           VARCHAR (100)    NULL,
    [City]             VARCHAR (100)    NULL,
    [Language]         VARCHAR (10)     NULL,
    [OrganizationName] VARCHAR (200)    NULL,
    [OrganizationType] VARCHAR (50)     NULL,
    [Qualification]    VARCHAR (50)     NULL,
    [Source]           VARCHAR (100)    NULL,
    [Latitude]         DECIMAL (10, 7)  NULL,
    [Longitude]        DECIMAL (10, 7)  NULL,
    [Batch]            VARCHAR (100)    NULL,
    [Created]          DATETIME         NULL,
    [Updated]          DATETIME         NULL,
    [Deleted]          BIT              NULL,
    [GoogleLocation]   VARCHAR (1000)   NULL,
    [CustomField1]     VARCHAR (500)    NULL,
    [CustomField2]     VARCHAR (500)    NULL,
    [Title]            VARCHAR (100)    NULL,
    [ZipCode]          VARCHAR (50)     NULL,
    [WebSite]          VARCHAR (200)    NULL,
    [LinkedIn]         VARCHAR (50)     NULL,
    [GooglePlus]       VARCHAR (50)     NULL,
    [Twitter]          VARCHAR (50)     NULL,
    [Facebook]         VARCHAR (50)     NULL,
    [Skype]            VARCHAR (50)     NULL,
    [Sector]           VARCHAR (200)    NULL,
    CONSTRAINT [PK_PotentialUsers] PRIMARY KEY CLUSTERED ([PotentialUserId] ASC)
);

