CREATE TABLE [dbo].[UserProperties] (
    [UserId]                  INT              NOT NULL,
    [NexsoUserId]             UNIQUEIDENTIFIER NULL,
    [Agreement]               VARCHAR (50)     NULL,
    [SkypeName]               VARCHAR (100)    NULL,
    [Twitter]                 VARCHAR (100)    NULL,
    [FaceBook]                VARCHAR (100)    NULL,
    [Google]                  VARCHAR (100)    NULL,
    [LinkedIn]                VARCHAR (100)    NULL,
    [OtherSocialNetwork]      VARCHAR (100)    NULL,
    [City]                    VARCHAR (100)    NULL,
    [Region]                  VARCHAR (100)    NULL,
    [Country]                 VARCHAR (100)    NULL,
    [PostalCode]              VARCHAR (100)    NULL,
    [Telephone]               VARCHAR (100)    NULL,
    [Address]                 VARCHAR (200)    NULL,
    [FirstName]               VARCHAR (100)    NULL,
    [LastName]                VARCHAR (100)    NULL,
    [email]                   VARCHAR (200)    NULL,
    [CustomerType]            INT              NULL,
    [NexsoEnrolment]          INT              NULL,
    [AllowNexsoNotifications] INT              NULL,
    [Language]                INT              NULL,
    [Latitude]                DECIMAL (10, 7)  NULL,
    [Longitude]               DECIMAL (10, 7)  NULL,
    [GoogleLocation]          VARCHAR (1000)   NULL,
    [Bio]                     VARCHAR (500)    NULL,
    [ProfilePicture]          UNIQUEIDENTIFIER NULL,
    [BannerPicture]           UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_UserProperties] PRIMARY KEY CLUSTERED ([UserId] ASC)
);

